# Builds the app and runs unit tests on push
name: Build and test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    # Run this job only if the pull request is not a draft
    if: github.event.pull_request.draft == false
    name: Build app and execute unit tests on Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle # Enables Gradle caching for faster builds

      - name: Print project directory content
        run: |
          echo "Current directory is: ${GITHUB_WORKSPACE}"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant permission to Gradle
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      # Upload test reports only if the test step fails
      - name: Archive test reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-reports
          path: |
            ./**/build/reports/
